# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    if: ${{ !contains(toJson(github.event.commits.*.message), '#skip') && github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  success_notification:
    name: Success notification
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: "Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9"
        if: success()
        with:
          args: A new version of Pokedex deployed to https://full-stack-open-pokedex-megaeonise.fly.dev/ by ${{github.actor}}
  failure_notification:
    name: Failure notification
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: "Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9"
        if: failure()
        with:
          args: Build failed. Commit https://github.com/megaeonise/full-stack-open-pokedex/commit/${{github.sha}} by ${{github.actor}} broke the build :(
