name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

      - name: Now it is
        run: |
          date
      - name: Directory content
        run: |
          ls -l
  # a_test_job:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: github context
  #       env:
  #         GITHUB_CONTEXT: ${{ toJson(github) }}
  #       run: echo "$GITHUB_CONTEXT"
  #     - name: commits
  #       env:
  #         COMMITS: ${{ toJson(github.event.commits) }}
  #       run: echo "$COMMITS"
  #     - name: commit messages
  #       env:
  #         COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
  #       run: echo "$COMMIT_MESSAGES"
  #     - name: includes a string
  #       env:
  #         COMMIT_MESSAGES: ${{ contains(toJson(github.event.commits.*.message), '#skip') }}
  #       run: echo "$COMMIT_MESSAGES"
  #     - name: does it work
  #       env:
  #         TEST: ${{ !contains(toJson(github.event.commits.*.message), '#skip') && github.event_name == 'push' }}
  #       run: echo "$TEST"
